### ISSUE TITLE
Automate the installation

### ISSUE THREAD

**Issue by Arkduke** [Typh0n12/SpotifyPlaylistDownloader#1]
`setup.py` can be added to automate the installation process.
Installation can be done by simply running  `python setup.py install`.

**Comment by C4TT0** [comment]
> `setup.py` can be added to automate the installation process. Installation can be done by simply running `python setup.py install`.

This seems a good idea. If you know python3 then i would suggest why not you contribute to it in the form of pull requests

**Comment by Arkduke** [comment]
can you add the tag of **hacktoberfest**?
